# Generated by Django 4.1.1 on 2022-09-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40, verbose_name="상품이름")),
                ("price", models.IntegerField(verbose_name="상품가격")),
                ("delivery_fee", models.IntegerField(verbose_name="배송비")),
            ],
        ),
    ]
